/* Generated by scripts/build_gallery.py -- do not edit by hand.
   Add images to images/gallery/ and captions to data/captions.json, then rerun. */
window.GALLERY = [
  {
    "src": "images/gallery/pombe_patches.jpg",
    "caption": "Pombe patches"
  }
];
