/* Generated by scripts/build_gallery.py -- do not edit by hand.
   Add images to images/gallery/ and captions to data/captions.json, then rerun. */
window.GALLERY = [
  {
    "src": "images/gallery/pombe-lifeact.webp",
    "caption": "Live S. pombe expressing LifeAct-GFP"
  },
  {
    "src": "images/gallery/pombe-myo1-fimbrin.webp",
    "caption": "Live S. pombe expressing GFP-tagged myosin-1 and mCherry-tagged fimbrin"
  }
];
