#!/usr/bin/env python3
"""
Regenerate js/gallery.js from whatever is sitting in images/gallery/.

Workflow: drop image files into images/gallery/, optionally add a caption
for each in data/captions.json, then run this (CI runs it on every push).
Anything without a caption gets one derived from its filename, so a file
dropped in with no config still shows up sensibly.

Run:  python scripts/build_gallery.py
"""

import io
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
IMG_DIR = os.path.join(ROOT, "images", "gallery")
CAPTIONS = os.path.join(ROOT, "data", "captions.json")
OUT = os.path.join(ROOT, "js", "gallery.js")

EXTS = (".jpg", ".jpeg", ".png", ".gif", ".webp", ".avif")

HEADER = """/* Generated by scripts/build_gallery.py -- do not edit by hand.
   Add images to images/gallery/ and captions to data/captions.json, then rerun. */
window.GALLERY = """


def pretty(name):
    stem = os.path.splitext(name)[0]
    for prefix in ("pombe-", "anim-", "algae-", "img-"):
        if stem.startswith(prefix):
            stem = stem[len(prefix):]
    return stem.replace("-", " ").replace("_", " ").strip().capitalize()


def main():
    captions = {}
    if os.path.exists(CAPTIONS):
        with io.open(CAPTIONS, encoding="utf-8") as fh:
            captions = json.load(fh)
        captions.pop("_comment", None)

    files = []
    if os.path.isdir(IMG_DIR):
        files = sorted(f for f in os.listdir(IMG_DIR)
                       if f.lower().endswith(EXTS) and not f.startswith("."))

    entries = [{"src": "images/gallery/" + f,
                "caption": captions.get(f) or pretty(f)}
               for f in files]

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with io.open(OUT, "w", encoding="utf-8") as fh:
        fh.write(HEADER)
        fh.write(json.dumps(entries, indent=2, ensure_ascii=False))
        fh.write(";\n")

    print("gallery.js written with %d image(s)." % len(entries))
    missing = [f for f in files if f not in captions]
    if missing:
        print("  no caption yet for: " + ", ".join(missing))


if __name__ == "__main__":
    main()
